owner: enzoglt
repo: qualimenti-uptime

sites:
  - name: Shop Qualimenti
    url: https://shop.qualimenti.com
    icon: https://raw.githubusercontent.com/enzoglt/qualimenti-uptime/master/assets/quali-favicon.png
  - name: App Qualimenti
    url: https://app.qualimenti.com
    icon: https://raw.githubusercontent.com/enzoglt/qualimenti-uptime/master/assets/quali-favicon.png
  - name: Q-Events
    url: https://q-events.it
    icon: https://raw.githubusercontent.com/enzoglt/qualimenti-uptime/master/assets/quali-favicon.png
  - name: Nginx Proxy
    check: "tcp-ping"
    url: $NGINX_PROXY
    port: 81
    icon: https://nginxproxymanager.com/icon.png

status-website:
  name: Qualimenti Uptime Monitoring
  baseUrl: /
  theme: dark
  favicon: https://raw.githubusercontent.com/enzoglt/qualimenti-uptime/master/assets/quali-favicon.png
  logoUrl: https://raw.githubusercontent.com/enzoglt/qualimenti-uptime/master/assets/quali-logo.svg
  introTitle: "Uptime monitoring page for Qualimenti websites"
  introMessage: Find below the list of our websites with live status updates

assignees:
  - enzoglt
