owner: enzoglt
repo: qualimenti-uptime

sites:
  - name: Shop Qualimenti
    url: https://shop.qualimenti.com
    icon: https://raw.githubusercontent.com/enzoglt/qualimenti-uptime/master/assets/quali-favicon.png
  - name: App Qualimenti
    url: https://app.qualimenti.com
    icon: https://raw.githubusercontent.com/enzoglt/qualimenti-uptime/master/assets/quali-favicon.png
  - name: Q-Events
    url: https://q-events.it
    icon: https://raw.githubusercontent.com/enzoglt/qualimenti-uptime/master/assets/quali-favicon.png

status-website:
  theme: dark
  favicon: https://raw.githubusercontent.com/enzoglt/qualimenti-uptime/master/assets/quali-favicon.png
  baseUrl: /qualimenti-uptime
  logoUrl: https://raw.githubusercontent.com/enzoglt/qualimenti-uptime/master/assets/quali-logo.svg
  name: Qualimenti Uptime Monitoring
  introTitle: "Uptime monitoring page for Qualimenti websites"
  introMessage: Find below the list of our websites with live status updates
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - enzoglt
